name: CI
on: push
jobs:
  smoke-test:
    strategy:
      matrix:
        runs-on: [4.x, 6.x, 8.x, 9.x, 10.x, 11.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: .
        with:
          version: 0.5.0
      - run: zig run src/main.zig
        working-directory: test
