name: CI
on: push
jobs:
  smoke-test:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: .
        with:
          version: 0.5.0
      - run: zig run src/main.zig
        working-directory: test
