name: CI
on: push
jobs:
  smoke-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
      - uses: goto-bus-stop/setup-zig@3fadddf
        with:
          version: 0.5.0
      - run: zig run src/main.zig
        working-directory: test
